apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sample-api
resources:
- namespace.yaml
- ../../base
- ingress.yaml
- horizontal-pod-autoscaler.yaml
- service-monitor.yaml
- prometheus-rule.yaml
- grafana-dashboard.yaml
images:
- name: ghcr.io/one2ndpiece/sample-api
  newName: ghcr.io/one2ndpiece/sample-api
  newTag: sha-ed3e64e03e923a80adcc8920e17aec258bd3ad52
