apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sample-api
resources:
- namespace.yaml
- ../../base
- ingress.yaml
- horizontal-pod-autoscaler.yaml
- service-monitor.yaml
- prometheus-rule.yaml
- grafana-dashboard.yaml
images:
- name: ghcr.io/one2ndpiece/sample-api
  newName: ghcr.io/one2ndpiece/sample-api
  newTag: sha-63543cd08930e069d1b8d677bfc18d974c0477e1
